// <auto-generated />
namespace TvAIr.Core;

/// <summary>Directory.Build.propsから生成されるTvAIr製品版・Plugin SDK・Plugin Host契約の正本。</summary>
internal static class TvAIrVersionContract
{
    public const string ProductName = "TvAIr";
    public const string ProductVersion = "1.0.4";
    public const string PluginSdkVersion = "1.0.0";
    public const string PluginHostContractVersion = "1.0.0";
    public const string MinimumSupportedPluginHostContractVersion = "1.0.0";
    public const int PluginCompatibilityMajor = 1;
    public const int LegacyPluginMajor = 0;
    public const string PublicContractName = "release_contract";
    public const string PluginHostContractName = "plugin-host-foundation";

    public static bool IsLegacyZeroMajor(string? version)
    {
        if (string.IsNullOrWhiteSpace(version)) return false;
        return global::System.Version.TryParse(NormalizeVersion(version), out var parsed) && parsed.Major == LegacyPluginMajor;
    }

    public static bool IsSupportedPluginContract(string? version)
    {
        if (string.IsNullOrWhiteSpace(version)) return true;
        return global::System.Version.TryParse(NormalizeVersion(version), out var parsed)
            && parsed.Major == PluginCompatibilityMajor
            && parsed.CompareTo(new global::System.Version(MinimumSupportedPluginHostContractVersion)) >= 0;
    }

    public static bool IsFutureUnsupportedPluginContract(string? version)
    {
        if (string.IsNullOrWhiteSpace(version)) return false;
        return global::System.Version.TryParse(NormalizeVersion(version), out var parsed)
            && parsed.Major > PluginCompatibilityMajor;
    }

    public static string NormalizeVersion(string value)
    {
        var v = value.Trim();
        if (v.StartsWith("v", global::System.StringComparison.OrdinalIgnoreCase)) v = v[1..];
        var dash = v.IndexOf('-');
        if (dash >= 0) v = v[..dash];
        return v.Replace('_', '.');
    }
}
