// <auto-generated />
namespace TvAIrPlugin;

/// <summary>Directory.Build.propsから生成されるTvAIrPlugin SDK 1.0.0以降の公開契約正本。</summary>
public static class TvAIrPluginSdkContract
{
    public const string SdkVersion = "1.0.0";
    public const string HostContractVersion = "1.0.0";
    public const string MinimumSupportedHostContractVersion = "1.0.0";
    public const int CompatibilityMajor = 1;

    public static bool IsCompatibleHostMajor(string? hostContractVersion)
    {
        if (string.IsNullOrWhiteSpace(hostContractVersion)) return true;
        return global::System.Version.TryParse(NormalizeVersion(hostContractVersion), out var parsed)
            && parsed.Major == CompatibilityMajor
            && parsed.CompareTo(new global::System.Version(MinimumSupportedHostContractVersion)) >= 0;
    }

    public static string NormalizeVersion(string value)
    {
        var v = value.Trim();
        if (v.StartsWith("v", global::System.StringComparison.OrdinalIgnoreCase)) v = v[1..];
        var dash = v.IndexOf('-');
        if (dash >= 0) v = v[..dash];
        return v.Replace('_', '.');
    }
}
